### ISSUE TITLE
On dit Portfolio 😆

### ISSUE THREAD

**Issue by nobodyw** [jessieln/portofolio#3]
Portfolio pas portofolio
Nan nan portorica 😜

**Comment by jessieln** [comment]
Mdrrr mais tu sors d'où toi laisses moi tranquille 😂

**Comment by nobodyw** [comment]
🤣 c'est ton ancien collègue ouesh

**Comment by nobodyw** [comment]
![Screenshot_20220205-164153](https://user-images.githubusercontent.com/24476074/159143616-54d57b7a-5e92-4c98-b220-6930653ca706.jpg)

**Comment by jessieln** [comment]
Le meilleur des anciens collègues , azy bientôt tu viens à la Casa ça fait
longtemps
